version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: app/Dockerfile  # Dockerfile 경로
    image: my-fastapi-app:latest  # 빌드된 이미지 이름과 태그를 명시적으로 설정
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - /Users/munhyobeom/PycharmProjects/test/app/data
    environment:
      DATABASE_URL: "mysql+pymysql://hbmoon:12312322@db:3306/mydb"  # MySQL 연결 정보
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: first-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 12312322
      MYSQL_DATABASE: mydb
      MYSQL_USER: hbmoon
      MYSQL_PASSWORD: 12312322
    ports:
      - "3306:3306"  # MySQL 포트
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:  # MySQL 데이터 볼륨